/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FormSubmission {
  'id' : bigint,
  'projectType' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'preferredDate' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface Property {
  'id' : bigint,
  'title' : string,
  'bedrooms' : bigint,
  'area' : bigint,
  'description' : string,
  'imageTag' : string,
  'bathrooms' : bigint,
  'price' : bigint,
  'location' : string,
}
export interface Service {
  'id' : bigint,
  'title' : string,
  'icon' : string,
  'description' : string,
  'category' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addFormSubmission' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'addProperty' : ActorMethod<
    [string, string, bigint, string, bigint, bigint, bigint, string],
    bigint
  >,
  'addService' : ActorMethod<[string, string, string, string], bigint>,
  'getAllFormSubmissions' : ActorMethod<[], Array<FormSubmission>>,
  'getAllProperties' : ActorMethod<[], Array<Property>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'seedSampleData' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];